# Generated by Django 3.1.2 on 2021-05-07 15:11

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default='slug', null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('parent', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('order_payment_mode', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('VISA / MASTERCARD', 'VISA / MASTERCARD '), ('UPI', 'UPI'), ('PAYTM', 'PAYTM')], max_length=25, null=True)),
                ('status', models.CharField(choices=[('Order Recieved', 'Order Recieved'), ('Order Accepted', 'Order Accepted'), ('Out for delivery ', 'Our for delivery '), ('Deliverd', 'Delivered')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(help_text='Example: 9489237834', max_length=10, null=True)),
                ('address_line_1', models.CharField(max_length=300)),
                ('address_line_2', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress_Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_id', models.IntegerField(null=True)),
                ('description', models.CharField(default='', max_length=150, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('unit', models.CharField(choices=[('Kg', 'Kg'), ('sq. meter', 'sq. meter'), ('piece', 'piece'), ('gm', 'gm'), ('ft', 'ft'), ('meter', 'meter'), ('inch', 'inch'), ('length * thickness* breadth', 'length * thickness* breadth'), ('length * breadth', 'length * breadth')], max_length=150, null=True)),
                ('dimension', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('Avaibility', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.shippingaddress_customer'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.IntegerField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
