# Generated by Django 3.0.14 on 2021-05-11 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20210511_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress_customer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='shippingaddress_customer',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
