# Generated by Django 3.0.14 on 2021-05-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210511_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.OrderItem'),
        ),
    ]
