# Generated by Django 3.0.14 on 2021-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210511_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING'), (4, 'PAY ON DELIVERY')], default=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_mode',
            field=models.CharField(choices=[(1, 'Cash On Delivery'), (2, 'Pay now')], max_length=25, null=True),
        ),
    ]
