# Generated by Django 3.0.14 on 2021-05-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210511_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_payment_mode',
            field=models.IntegerField(choices=[(1, 'Cash On Delivery'), (2, 'Pay now')], max_length=25, null=True),
        ),
    ]
