# Generated by Django 3.0.14 on 2021-05-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_shippingaddress_customer_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_of_payment',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
